### ISSUE TITLE
when damping is negative and you scroll the view, the woobleview green color remains visible at random rows 

### ISSUE THREAD

**Issue by mdcoin** [inFullMobile/WobbleView#13]
Ok, I'm not sure how to properly explain this, let me know if you need a video to demonstrate and replicate the issue.

A little background:
When you release the cell and it touches the right corner it still oscillates a little until it comes to a full stop, it oscillates horizontally a little into the cell frame and outside it, this is by design and it's normal behavior. 

To replicate the issue you will have to swipe a cell and after you release it as soon as it touches the right corner you will have to scroll the view and you will see that every other row now has a negative damping that didn't finish (green color)  ( the right edge of the cell is now curved and you can see a little green color because it was still finishing oscillating when you scrolled the view and it just froze in that state, this affects random cells, not just the one you swiped).

Thanks.

**Comment by kondratk** [comment]
Fixed in PR #16 :)
