### ISSUE TITLE
README claims minimum target of 7.0+ but podspec lists 8.0

### ISSUE THREAD

**Issue by MrMatthewDavis** [inFullMobile/WobbleView#4]
This prevents anyone whose app runs on 7.0-7.1 from using Cocoapods to install this library. Has the minimum target actually changed to 8.0 or will it still run on 7.0+?

**Comment by wojteklu** [comment]
Hi @mad102190. Unfortunately it is not possible using CocoaPods. Please check https://github.com/CocoaPods/swift/issues/22. It will run on 7.0+, but you should install project manually, not using CocoaPods.
